FROM node:24-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build

# Production stage
FROM caddy:alpine
COPY --from=build /app/dist /srv
COPY production/Caddyfile /etc/caddy/Caddyfile
EXPOSE 80 443
